title: George Ismailaj
logo: /assets/img/1ssm4.png
#description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
